version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-microservice:latest
    container_name: auth_app
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - auth-network
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/api-docs']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  mongo:
    image: mongo:6.0
    container_name: auth_mongo
    command: mongod --noauth
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - auth-network
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

networks:
  auth-network:
    driver: bridge

volumes:
  mongo-data:
    name: auth_mongo_data
